version: '3.8'

services:
  # NATS Message Bus with JetStream
  nats:
    image: nats:2.10-alpine
    container_name: neuralux-nats
    command:
      - "--jetstream"
      - "--store_dir=/data"
      - "--max_memory_store=2GB"
      - "--max_file_store=10GB"
      - "--http_port=8222"
    ports:
      - "4222:4222"   # Client connections
      - "8222:8222"   # HTTP monitoring
      - "6222:6222"   # Routing port for clustering
    volumes:
      - nats-data:/data
    networks:
      - neuralux-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: neuralux-redis
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - neuralux-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: neuralux-qdrant
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - neuralux-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  neuralux-net:
    driver: bridge

volumes:
  nats-data:
    driver: local
  redis-data:
    driver: local
  qdrant-data:
    driver: local

